version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: hackathon_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hackathon_db
      POSTGRES_USER: hackathon_user
      POSTGRES_PASSWORD: hackathon_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - hackathon_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hackathon_pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hackathon.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    networks:
      - hackathon_network

volumes:
  postgres_data:

networks:
  hackathon_network:
    driver: bridge
